### ISSUE TITLE
Hacked Client?

### ISSUE THREAD

**Issue by mtgsquad** [superblaubeere27/ClientBase#10]
If Its Hacked Then Its Useless...

**Comment by YeahOMA** [comment]
> If Its Hacked Then Its Useless...

The fuck do you mean "hacked"

**Comment by mtgsquad** [comment]
> > If Its Hacked Then Its Useless...
> 
> The fuck do you mean "hacked"

Is A Client With Hacks Or Not....

**Comment by laika-cosmonaut** [comment]
this is obviously some kid that is all like "hAcKiNg rUiNs ThE gAmE", ignore it.

**Comment by mtgsquad** [comment]
> this is obviously some kid that is all like "hAcKiNg rUiNs ThE gAmE", ignore it.

Uhhh, i want hacks... like I wanted a long time ago, then i quit on the client so yeah..

**Comment by ghost** [comment]
> > > If Its Hacked Then Its Useless...
> > 
> > 
> > The fuck do you mean "hacked"
> 
> Is A Client With Hacks Or Not....


If Its Hacked Then Its Useless...

LOL so true mtgsquad allah :pray:
