### ISSUE TITLE
forgeSrc could not be downlaoded

### ISSUE THREAD

**Issue by Spaceish** [superblaubeere27/ClientBase#13]
i am getting this error when i run the command `gradlew setupDecompWorkspace eclipse build`:
`> Task :compileJava FAILED`

`FAILURE: Build failed with an exception.`

`* What went wrong:`
`Could not resolve all files for configuration ':forgeGradleMc'.`
`> Could not find forgeSrc.jar (net.minecraftforge:forgeSrc:1.8.9-11.15.1.1722).`
`  Searched in the following locations:`
     ` http://files.minecraftforge.net/maven/net/minecraftforge/forgeSrc/1.8.9-11.15.1.1722/forgeSrc-1.8.9-11.15.1.1722.jar`

**Comment by MOMIN5** [comment]
path to your folder and run this in console `gradlew setupDecompWorkspace`

**Comment by Spaceish** [comment]
it worked thanks
