### ISSUE TITLE
Error when playing a world

### ISSUE THREAD

**Issue by Spaceish** [superblaubeere27/ClientBase#9]
When I try to create or play a world it stucks at loading world , building terrain.
Here is my latest log:
[latest.log](https://github.com/superblaubeere27/ClientBase/files/5597967/latest.log)

**Comment by superblaubeere27** [comment]
The program luckily told you what's wrong with it: `java.lang.OutOfMemoryError: GC overhead limit exceeded`. That means that your programm has not enough memory to operate. If you want to know how to fix it, lookup this error via google, you should find some good explainations and fixes ;D
